const characters = [ "Airi",
  "Aleister",
  "Alice",
  "Allain",
  "Amily",
  "Annette",
  "Aoi",
  "Arduin",
  "Arum",
  "Astrid",
  "Ata",
  "Aya",
  "Azzen'Ka",
  "Baldum",
  "Bright",
  "Butterfly",
  "Capheny",
  "Celica",
  "Chaugnar",
  "Cresht",
  "D'Arcy",
  "Dextra",
  "Diao Chan",
  "Dirak",
  "Eland'orr",
  "Elsu",
  "Enzo",
  "Errol",
  "Fennik",
  "Florentino",
  "Gildur",
  "Grakk",
  "Hayate",
  "IGGY",
  "Ignis",
  "Illumia",
  "Ishar",
  "Jinna",
  "Kahlii",
  "Keera",
  "Kil'Groth",
  "Kriknak",
  "Krixi",
  "Krizzix",
  "Lauriel",
  "Laville",
  "Liliana",
  "Lindis",
  "Lorion",
  "Lu Bu",
  "Lumburr",
  "Maloch",
  "Marja",
  "Max",
  "Mganga",
  "Mina",
  "Moren",
  "Mortos",
  "Murad",
  "Nakroth",
  "Natalya",
  "Omega",
  "Omen",
  "Ormarr",
  "Paine",
  "Preyta",
  "Qi",
  "Quillen",
  "Raz",
  "Riktor",
  "Rouie",
  "Rourke",
  "Roxie",
  "Ryoma",
  "Sephera",
  "Sinestrea",
  "Skud",
  "Slimz",
  "Super Man",
  "Taara",
  "Tachi",
  "TeeMee",
  "Teeri",
  "Tel'Annas",
  "Thane",
  "The Flash",
  "Thorne",
  "Toro",
  "Tulen",
  "Valhein",
  "Veera",
  "Veres",
  "Violet",
  "Volkath",
  "Wiro",
  "Wisp",
  "Wonder Woman",
  "WuKong",
  "Xeniel",
  "Y'bneth",
  "Yan",
  "Yena",
  "Yorn",
  "Yue",
  "Zanis",
  "Zata",
  "Zephys",
  "Zill",
  "Zip",
  "Zuka",
  "Kain"
];

const startButton = document.getElementById("startButton");
const resultDiv = document.getElementById("result");

startButton.addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * characters.length);
  const selectedCharacter = characters[randomIndex];
  resultDiv.innerHTML = selectedCharacter;
  resultDiv.classList.remove("hidden");
});

const colors = ["red", "blue", "green", "orange", "purple", "pink"];

startButton.addEventListener("click", () => {
  const randomIndex = Math.floor(Math.random() * characters.length);
  const selectedCharacter = characters[randomIndex];
  resultDiv.innerHTML = selectedCharacter;
  resultDiv.classList.remove("hidden");

  // เปลี่ยนสีสุ่มเมื่อกดปุ่ม
  const randomColor = colors[Math.floor(Math.random() * colors.length)];
  resultDiv.style.color = randomColor;
});